spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3307/gymentality?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=LaraCr0ft84
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

server.port=8080

app.jwt.secret=gymentality-super-secret-key-for-daw-project-2026-very-secure
app.jwt.expiration-ms=86400000
